spring.application.name=candidateapi
server.port=8075
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}
